name: gurps_ability_builder_web
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  protobuf: ^0.13.11
  rxdart: ^0.22.0
  #-- enable if flutter_web works with other flutter plugins and remove lib/widgets/type_ahead_textfield.dart
  # flutter_typeahead: ^1.6.1 
  gurps_modifiers:
    git: 
      url: https://github.com/mjeffw/gurps_modifiers

dev_dependencies:
  build_runner: ^1.6.1
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
