/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter_web/widgets.dart';

class GurpsIcons {
  GurpsIcons._();

  static const _kFontFam = 'GurpsIcons';

  static const IconData gun = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData long_branch_oss =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData noun_crawl_485414 =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData noun_dead_body_1161055 =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData noun_human_1307595 =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData noun_kneel_486922 =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData noun_sit_1506535 =
      const IconData(0xe806, fontFamily: _kFontFam);
}
